'use client';

import Link from 'next/link';
import { Clipboard, Download } from 'lucide-react';
import type { ArtifactSet, Incident, WorkflowStage } from '@/lib/types';
import { artifactText, downloadArtifact, downloadAllArtifacts } from '@/lib/downloadArtifact';

function Detail({ label, value }: { label: string; value: string }) { return <><span className="text-[var(--color-text-secondary)]">{label}</span><span className="text-[var(--color-text-primary)] truncate">{value}</span></>; }

export function StageDetail({ name, incident, stage, artifacts }: { name: string; incident: Incident; stage?: WorkflowStage; artifacts: ArtifactSet }) {
  if (name === 'Upload Incident') return <div className="space-y-3"><div className="flex gap-2 text-sm text-[var(--color-text-primary)]"><span>{incident.provider}</span><span className="rounded-full bg-[var(--color-accent-soft)] px-2 py-0.5 text-xs text-[var(--color-accent)]">{incident.severity}</span></div><pre className="max-h-24 overflow-hidden rounded-[var(--radius-sm)] bg-[var(--color-code-bg)] p-3 text-xs text-[var(--color-code-text)] whitespace-pre-wrap">{incident.summary}</pre><Link href={`/incidents/${incident.id}`} className="text-xs text-[var(--color-accent)]">View full report</Link></div>;
  if (name === 'AI Extracts Structure') return <div className="grid grid-cols-[140px_1fr] gap-y-2 text-sm"><Detail label="Provider" value={incident.provider} /><Detail label="Severity" value={incident.severity} /><Detail label="Detected format" value="Plain incident report" /><Detail label="Services" value={incident.summary.slice(0, 80)} /></div>;
  if (name === 'System Identifies Root Cause') return <div><span className="inline-block rounded-full bg-[var(--color-accent-soft)] px-2 py-1 text-xs font-medium text-[var(--color-accent)]">Infrastructure</span><p className="mt-3 text-sm leading-6 text-[var(--color-text-secondary)]">The incident indicates physical infrastructure damage in a regional availability zone, causing cascading service degradation and elevated error rates.</p></div>;
  if (name === 'Generate Guardrails') { const entries = Object.entries(artifacts).filter(([, value]) => value) as Array<[keyof ArtifactSet, NonNullable<ArtifactSet[keyof ArtifactSet]>]>; return <div className="flex flex-wrap gap-2">{entries.map(([type]) => <Link key={type} href={`/dashboard#guardrail-review-queue`} className="rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-[var(--color-accent-soft)] px-3 py-2 text-xs font-medium text-[var(--color-accent)]">{type === 'policy' ? 'OPA Policy' : type === 'iac' ? 'Terraform Patch' : type === 'alerts' ? 'Alert Rule' : type === 'runbook' ? 'Runbook' : type}</Link>)}</div>; }
  const entries = Object.entries(artifacts).filter(([, value]) => value) as Array<[keyof ArtifactSet, NonNullable<ArtifactSet[keyof ArtifactSet]>]>;
  return <div><p className="text-sm text-[var(--color-text-secondary)]">Awaiting review</p><div className="mt-3 flex flex-wrap gap-2">{entries.length > 0 && <button type="button" onClick={() => downloadAllArtifacts(entries as any)} className="inline-flex items-center gap-2 rounded-[var(--radius-sm)] border border-[var(--color-border)] px-3 py-2 text-xs text-[var(--color-text-primary)]"><Download size={14} /> Download All</button>}{entries.map(([type, artifact]) => <span key={type} className="inline-flex items-center gap-2 text-xs text-[var(--color-text-secondary)]">{type}<button type="button" title="Copy" onClick={() => navigator.clipboard.writeText(artifactText(artifact as any))}><Clipboard size={13} /></button><button type="button" title="Download" onClick={() => downloadArtifact(`${type}.txt`, artifactText(artifact as any))}><Download size={13} /></button></span>)}</div></div>;
}
